export default [
  { "id": "1", "name": "Invoice in Process" },
  { "id": "2", "name": "Check Issued to Vendor" },
  { "id": "3", "name": "AP Vendor Invoice" },
  { "id": "4", "name": "Bill of Lading" },
  { "id": "5", "name": "Ship Ticket" },
  { "id": "6", "name": "Customer Invoice" },
  { "id": "7", "name": "NO READ BARCODE" },
  { "id": "8", "name": "Fuel Delivery Ticket" },
  { "id": "9", "name": "Per Diem" },
  { "id": "10", "name": "Weight Ticket" },
  { "id": "11", "name": "Check List" },
  { "id": "12", "name": "Safety Form" },
  { "id": "13", "name": "Shop/Breakdown Form" },
  { "id": "14", "name": "Exception Form" },
  { "id": "15", "name": "IT Forms" },
  { "id": "16", "name": "Debit Memo" },
  { "id": "17", "name": "Check Printed Pending Post" },
  { "id": "18", "name": "Cancelled Check" },
  { "id": "19", "name": "Check Cancelled Pending Post" },
  { "id": "20", "name": "Tampa Autbra Load Summary" },
  { "id": "21", "name": "Meter Route" },
  { "id": "22", "name": "Customer BP Invoice" },
  { "id": "23", "name": "Quality Control" },
  { "id": "24", "name": "Pending" },
  { "id": "25", "name": "Demmurage Ticket Form" },
  { "id": "26", "name": "P-14 Termination Form" },
  { "id": "27", "name": "P-14 On Leave" },
  { "id": "31", "name": "Other Form" },
  { "id": "37", "name": "HR Terms" },
  { "id": "38", "name": "Recruiting Applications" },
  { "id": "39", "name": "Safety Terminations" },
  { "id": "40", "name": "PUC" },
  { "id": "41", "name": "AVMS" },
  { "id": "42", "name": "Settlement Sheets" },
  { "id": "44", "name": "Safety Meeting Documents" },
  { "id": "47", "name": "Hours of Service" },
  { "id": "48", "name": "Unassigned Driving" },
  { "id": "50", "name": "Safety Bonuses and Awards" }
]